proxy:
  host: 192.168.201.201
  port: 3128

ec-pay:
  base-url: https://payment-stage.ecpay.com.tw

feign:
  client:
    config:
      default:
        loggerLevel: FULL
        readTimeout: 60000
        connectTimeout: 60000

logging.level:
  boilerplate.spring.feignclient.client: DEBUG